name: Check yarn
on: [push]
jobs:
  check-yarn:
    runs-on: ubuntu-latest
    name: Check yarn
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Nodes
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      
      - name: Check yarn version
        run: yarn --version
