name: Release
on:
  pull_request:
    types: [closed]
    branches:
      - release
      - "release/*"

permissions:
  contents: write
  packages: write

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Nodes
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: yarn
        
      - name: Install dependencies
        run: yarn install --immutable

      - name: Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn run version
