name: Release
on:
  pull_request:
    types: [closed]
    branches:
      - main
      - prerelease

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  version:
    name: Version
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Upgrade yarn
        run: yarn set version 3.2.0

      - name: Setup Nodes
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      # https://github.com/azu/lerna-monorepo-github-actions-release/blob/master/.github/workflows/publish.yml
      - name: Git identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Install dependencies
        run: yarn install --immutable

      - name: Set current version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          CURRENT_VERSION=$(node -p 'require("./lerna.json").version')
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV

      - name: Version
        run: |
          if [ ${{ github.base_ref }} = prerelease ]; then
            yarn run version --conventional-prerelease --preid beta --yes
          else
            yarn run version --conventional-graduate --yes
          fi
      
      - name: Publish
        run: yarn run publish --yes
