name: Yarn 3
on:
  push:
    branches:
      - release-flow

jobs:
  install:
    name: Use yarn 3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Nodes
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: yarn
      
      - name: Setup .yarnrc.yml
        run: |
          yarn config set npmScopes.my-org.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.my-org.npmAlwaysAuth true
          yarn config set npmScopes.my-org.npmAuthToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}

      - name: Check version
        run: yarn --version
    
      - name: Install
        run: yarn install --immutable
